### ISSUE TITLE
Fix getConfigTreeBuilder deprecation

### ISSUE THREAD

**Issue by Nirvanios** [jawira/doctrine-diagram-bundle#14]
Symfony warns me about deprecation, it's only about missing return type.

`Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "Jawira\DoctrineDiagramBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.`

**Comment by jawira** [comment]
Hi, it should be fixed in v0.3.1 thanks for reporting :)
