### ISSUE TITLE
Use custom server in Command?

### ISSUE THREAD

**Issue by Knallcharge** [jawira/doctrine-diagram-bundle#16]
Hi,

I was just checking out the bundle and love it! I only got one problem: Due to company policy https-traffic is intercepted and checked which unfortunately leads to a "file_get_contents(): SSL operation failed"-error when trying to generate png or svg. Using http on the plantuml-server instead of https resolves the problem for me.

I have seen that there is a Configuration-file in the bundle which doesn't seem to be used? (tried to change the server that way), also when using the command, it calls "convertWithServer" which then calls "return (new Client)->generateImage($puml, $format);", always using the SERVER-constant instead of a custom one which may be set using a parameter when calling the command or via a yaml-configuration.

So is it possible to add a way to change the server when using the command in some way? For now I can duplicate the command from the bundle and call the "(new Client)"-part with the custom server, but I guess it'd be nicer if that was possible with the command contained in the bundle.

Kind regards

**Comment by jawira** [comment]
Hello, I also like this bundle and I know it's a little bit abandoned.

Currently I have no free time, please give one or two weeks to see what I can do.

Thanks for your message :)

**Comment by Knallcharge** [comment]
Thanks for getting back! I have provided a minimal pull request that should do the job.
You may want to look at if you find the time, but no hurries :)

**Comment by Knallcharge** [comment]
Thanks for the quick merge! Also took me a short while to decide which letter to use ;)

I'm not using any pipline, but as stated in the original post, https leeds to an error in my company-environment, so I need to use http for now (or file an official security-request to not intercept traffic to plantuml.com but that'll take ages).

**Comment by jawira** [comment]
Hello, FYI now you can set server in command line and in doctrine_diagram.yaml

**Comment by knallcharge** [comment]
Great, thanks!
