### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by lsv** [jawira/doctrine-diagram-bundle#34]
With a postgres database, it will also dump all the "internal" postgre views. (pg_catalog, column_udt_usage, udt_privileges etc)

Next with `--size maxi` you would most likely also exeed the max width of the png as 4000px (I did...)

Other than it adds the postgre internal tables between the "real" tables (and therefor also missing some relation arrows)  it looks good.

**Comment by jawira** [comment]
Thank you very much for your feedback.

1. I will implement a way to exclude some tables and views in the future, this way you will be able to hide unwanted views.
2. png max width is a PlantUML limitation, which you can configure is you are converting "puml" diagram using PlantUML executable in your system (let me know if you need more info about this).

**Comment by jawira** [comment]
Hello, FYI now you can hide tables: 
https://jawira.github.io/doctrine-diagram-bundle/usage.html#excluding-tables

I will close the issue, thank you :)
