### ISSUE TITLE
no link between parts

### ISSUE THREAD

**Issue by cadot-eu** [jawira/doctrine-diagram-bundle#5]
I generate by
`sc jawira:doctrine:diagram`
but i have
![out](https://user-images.githubusercontent.com/97225403/149387938-1ec81352-822c-48f0-9681-53581ce7d6e9.png)

Are you a idea?

Thanks for your good tools ;-)

**Comment by jawira** [comment]
Hello, sorry for the delay.
I don't know what's the problem :/
Can you put a link if you are working in a public repo ? Maybe you can share a dump from your db ?

**Comment by jawira** [comment]
I will close this issue, but please contact me when you have more info to reproduce the problem.

**Comment by cadot-eu** [comment]
ok, thanks for your job, nice day
