### ISSUE TITLE
Allowing setting up background color

### ISSUE THREAD

**Issue by myselfhimself** [jawira/doctrine-diagram-bundle#8]
This tool comes in handy in turns with `bin/console make:entity` to check visually for Doctrine's schema changes. Thank you

For the SVG export it would be nice to have a white background instead of a transparent one.
This could be a new command line option providing a CSS or hex color eg. `--bgcolor`

**Comment by jawira** [comment]
Hello, as you can see background color is correctly set in svg diagram:

![image](https://user-images.githubusercontent.com/496541/200948453-b10e48e1-c8c0-4562-9df7-571a59709b3c.png)

Some programs doesn't show background properly. Also, when I use svg diagram in browsers, the background is correctly displayed (white background).

**Comment by myselfhimself** [comment]
Thank you and sorry for bothering!

**Comment by jawira** [comment]
It wasn't a problem at all, thank you for reporting :)

**Comment by jawira** [comment]
Hello, FYI now you can use themes in your diagrams 
https://jawira.github.io/doctrine-diagram-bundle/configuration.html

**Comment by myselfhimself** [comment]
Thank you Jawira, I am not using this project currently, but this will be
useful for readers of this thread!

Le lun. 12 févr. 2024 à 22:13, Jawira Portugal ***@***.***> a
écrit :
