### ISSUE TITLE
Avoid CRLF line endings

### ISSUE THREAD

**Issue by myselfhimself** [jawira/doctrine-diagram-bundle#9]
Hello it seems that the generator introduces CRLF line endings to generated .svg files.
This leads to Git errors when adding a .svg file:
`warning: CRLF will be replaced by LF in docs/database.svg.`

**Comment by jawira** [comment]
Yes, I'm aware of this issue, what I suggest is to create the following files at the root of your project:

Use `.gitattributes`, with this file git will automatically make the conversion when commit/push/pull changes:

```
# .gitattributes
*.php	text	eol=lf	diff=php
*.svg	text	eol=lf
*.phar	binary
```

File `.editorconfig`, this will configure your IDE to use the right end-of-line with svg files:

```
# .editorconfig
root = true

[*.svg]
charset = utf-8
end_of_line = lf
```

You can see that this project also defines these files (I just updated .gitattributes):

- <https://github.com/jawira/doctrine-diagram-bundle/blob/main/.editorconfig>
- <https://github.com/jawira/doctrine-diagram-bundle/blob/main/.gitattributes>

You might have some conflicts at the beginning with outdated branches, but then everything will be ok.
I use both files in all my projects.

**Comment by jawira** [comment]
Since using `.gitattributes` will solve your problem I will close this issue.
